CREATE TABLE "don_vi" (
  "ma_don_vi" varchar(50) PRIMARY KEY,
  "ten_don_vi" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "bo_phan" (
  "ma_bo_phan" varchar(50) PRIMARY KEY,
  "ten_bo_phan" varchar(255) NOT NULL,
  "ma_don_vi" varchar(50) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "vi_tri" (
  "ma_vi_tri" varchar(50) PRIMARY KEY,
  "ten_vi_tri" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "tai_khoan" (
  "ma_tai_khoan" varchar(50) PRIMARY KEY,
  "ten_tai_khoan" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "nhan_vien" (
  "ma_nhan_vien" varchar(50) PRIMARY KEY,
  "ho_ten_nhan_vien" varchar(255) NOT NULL,
  "ma_bo_phan" varchar(50) NOT NULL,
  "ma_vi_tri" varchar(50) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "kho" (
  "ma_kho" varchar(50) PRIMARY KEY,
  "ten_kho" varchar(255) NOT NULL,
  "dia_diem_kho" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "don_vi_tinh" (
  "ma_don_vi_tinh" varchar(50) PRIMARY KEY,
  "ten_don_vi_tinh" varchar(100) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "vat_tu" (
  "ma_vat_tu" varchar(50) PRIMARY KEY,
  "ten_vat_tu" varchar(255) NOT NULL,
  "loai_vat_tu" varchar(50) NOT NULL,
  "nhan_hieu_vat_tu" text,
  "quy_cach_vat_tu" text,
  "pham_chat_vat_tu" text,
  "ma_don_vi_tinh" varchar(50) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "phieu_nhap_kho" (
  "so_phieu" varchar(50) PRIMARY KEY,
  "ngay_lap_phieu" date NOT NULL,
  "ma_don_vi" varchar(50) NOT NULL,
  "ma_bo_phan" varchar(50) NOT NULL,
  "ma_tai_khoan_no" varchar(50) NOT NULL,
  "ma_tai_khoan_co" varchar(50) NOT NULL,
  "so_chung_tu" varchar(100),
  "ngay_chung_tu" date,
  "ma_kho" varchar(50) NOT NULL,
  "so_chung_tu_goc_kem_theo" text,
  "ma_nguoi_lap_phieu" varchar(50) NOT NULL,
  "ten_nguoi_giao_hang" varchar(255) NOT NULL,
  "ma_thu_kho" varchar(50) NOT NULL,
  "ma_ke_toan_truong" varchar(50) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "chi_tiet_phieu_nhap" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "so_phieu" varchar(50) NOT NULL,
  "ma_vat_tu" varchar(50) NOT NULL,
  "so_luong_theo_chung_tu" numeric(18,2),
  "so_luong_thuc_nhap" numeric(18,2) NOT NULL,
  "don_gia" numeric(18,2) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE INDEX ON "chi_tiet_phieu_nhap" ("so_phieu");

CREATE INDEX ON "chi_tiet_phieu_nhap" ("ma_vat_tu");

ALTER TABLE "bo_phan" ADD FOREIGN KEY ("ma_don_vi") REFERENCES "don_vi" ("ma_don_vi") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "nhan_vien" ADD FOREIGN KEY ("ma_bo_phan") REFERENCES "bo_phan" ("ma_bo_phan") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "nhan_vien" ADD FOREIGN KEY ("ma_vi_tri") REFERENCES "vi_tri" ("ma_vi_tri") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vat_tu" ADD FOREIGN KEY ("ma_don_vi_tinh") REFERENCES "don_vi_tinh" ("ma_don_vi_tinh") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_nhap_kho" ADD FOREIGN KEY ("ma_don_vi") REFERENCES "don_vi" ("ma_don_vi") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_nhap_kho" ADD FOREIGN KEY ("ma_bo_phan") REFERENCES "bo_phan" ("ma_bo_phan") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_nhap_kho" ADD FOREIGN KEY ("ma_tai_khoan_no") REFERENCES "tai_khoan" ("ma_tai_khoan") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_nhap_kho" ADD FOREIGN KEY ("ma_tai_khoan_co") REFERENCES "tai_khoan" ("ma_tai_khoan") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_nhap_kho" ADD FOREIGN KEY ("ma_nguoi_lap_phieu") REFERENCES "nhan_vien" ("ma_nhan_vien") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_nhap_kho" ADD FOREIGN KEY ("ma_thu_kho") REFERENCES "nhan_vien" ("ma_nhan_vien") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_nhap_kho" ADD FOREIGN KEY ("ma_ke_toan_truong") REFERENCES "nhan_vien" ("ma_nhan_vien") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_nhap_kho" ADD FOREIGN KEY ("ma_kho") REFERENCES "kho" ("ma_kho") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chi_tiet_phieu_nhap" ADD FOREIGN KEY ("so_phieu") REFERENCES "phieu_nhap_kho" ("so_phieu") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chi_tiet_phieu_nhap" ADD FOREIGN KEY ("ma_vat_tu") REFERENCES "vat_tu" ("ma_vat_tu") DEFERRABLE INITIALLY IMMEDIATE;






-- -- Fake data
-- -- don_vi
-- INSERT INTO don_vi (ma_don_vi, ten_don_vi)
-- VALUES
-- ('DV001', 'Bệnh viện Việt Nam'),
-- ('DV002', 'Phòng khám Việt Đức'),
-- ('DV003', 'Trung tâm Y tế Hà Nội');

-- -- bo_phan
-- INSERT INTO bo_phan (ma_bo_phan, ten_bo_phan, ma_don_vi)
-- VALUES
-- ('BP001', 'Khoa Dược', 'DV001'),
-- ('BP002', 'Khoa Xét nghiệm', 'DV002'),
-- ('BP003', 'Kho Vật tư', 'DV003');

-- -- tai_khoan
-- INSERT INTO tai_khoan (ma_tai_khoan, ten_tai_khoan)
-- VALUES
-- ('152', 'Nguyên vật liệu'),
-- ('153', 'Công cụ dụng cụ'),
-- ('331', 'Phải trả nhà cung cấp');

-- -- vi_tri
-- INSERT INTO vi_tri (ma_vi_tri, ten_vi_tri)
-- VALUES
-- ('VT001', 'Nhân viên'),
-- ('VT002', 'Thủ kho'),
-- ('VT003', 'Kế toán trưởng');

-- -- nhan_vien
-- INSERT INTO nhan_vien (
--   ma_nhan_vien,
--   ho_ten_nhan_vien,
--   ma_bo_phan,
--   ma_vi_tri
-- )
-- VALUES
-- ('NV001', 'Nguyễn Thị Lan', 'BP001', 'VT001'),
-- ('NV002', 'Trần Văn Minh', 'BP002', 'VT002'),
-- ('NV003', 'Phạm Thu Hương', 'BP003', 'VT003');

-- -- kho
-- INSERT INTO kho (ma_kho, ten_kho, dia_diem_kho)
-- VALUES
-- ('K001', 'Kho thuốc', 'Tầng 1'),
-- ('K002', 'Kho vật tư', 'Tầng 2'),
-- ('K003', 'Kho hóa chất', 'Tầng 3');

-- -- don_vi_tinh
-- INSERT INTO don_vi_tinh (ma_don_vi_tinh, ten_don_vi_tinh)
-- VALUES
-- ('DVT001', 'Hộp'),
-- ('DVT002', 'Chai'),
-- ('DVT003', 'Cái');

-- -- vat_tu
-- INSERT INTO vat_tu (
--   ma_vat_tu,
--   ten_vat_tu,
--   loai_vat_tu,
--   nhan_hieu_vat_tu,
--   quy_cach_vat_tu,
--   pham_chat_vat_tu,
--   ma_don_vi_tinh
-- )
-- VALUES
-- ('VT001', 'Găng tay y tế', 'vat_tu', 'Vglove', 'Hộp 100 cái', 'Tiệt trùng', 'DVT001'),
-- ('VT002', 'Cồn sát khuẩn', 'hang_hoa', 'BioPharma', 'Chai 500ml', 'Y tế', 'DVT002'),
-- ('VT003', 'Ống nghiệm', 'dung_cu', 'MedLab', 'Hộp 50 cái', 'Nhựa PP', 'DVT003');

-- -- phieu_nhap_kho
-- INSERT INTO phieu_nhap_kho (
--   so_phieu,
--   ngay_lap_phieu,
--   ma_don_vi,
--   ma_bo_phan,
--   ma_tai_khoan_no,
--   ma_tai_khoan_co,
--   so_chung_tu,
--   ngay_chung_tu,
--   ma_kho,
--   so_chung_tu_goc_kem_theo,
--   ma_nguoi_lap_phieu,
--   ten_nguoi_giao_hang,
--   ma_thu_kho,
--   ma_ke_toan_truong
-- )
-- VALUES
-- ('PN001', '2026-04-27', 'DV001', 'BP001', '152', '331', 'HD001', '2026-04-27', 'K001', 'Hóa đơn số 001', 'NV001', 'Lê Văn A', 'NV002', 'NV003'),
-- ('PN002', '2026-04-28', 'DV002', 'BP002', '152', '331', 'HD002', '2026-04-28', 'K002', 'Hóa đơn số 002', 'NV002', 'Trần Văn B', 'NV003', 'NV001'),
-- ('PN003', '2026-04-29', 'DV003', 'BP003', '153', '331', 'HD003', '2026-04-29', 'K003', 'Hóa đơn số 003', 'NV003', 'Phạm Văn C', 'NV001', 'NV002');

-- -- chi_tiet_phieu_nhap
-- INSERT INTO chi_tiet_phieu_nhap (
--   so_phieu,
--   ma_vat_tu,
--   so_luong_theo_chung_tu,
--   so_luong_thuc_nhap,
--   don_gia
-- )
-- VALUES
-- ('PN001', 'VT001', 50, 50, 120000),
-- ('PN002', 'VT002', 30, 30, 85000),
-- ('PN003', 'VT003', 100, 98, 15000);